### ISSUE TITLE
Repo outdated

### ISSUE THREAD

**Issue by mitechzone** [OfficeDev/office-fluent-ui-command-identifiers#11]
This repo hasn't been maintained for the last few years. There is no public information for command Ids or policy Ids for new features introduced over the past 4-5 years.

@nokafor @davidchesnut @microsoftopensource

**Comment by davidchesnut** [comment]
Thanks @mitechzone, I'm looking into the plan for this repo and will follow up.

**Comment by thisisevilevil** [comment]
bump, if this one could get an update that would be highly appreciated 👍

**Comment by davidchesnut** [comment]
Hi @thisisevilevil, sorry about that. I'm reaching out to folks today and might take a few more days to find the status, or owner.

**Comment by davidchesnut** [comment]
Just a quick update that @bcoard is taking a look at this issue.

**Comment by mitechzone** [comment]
> Just a quick update that @bcoard is taking a look at this issue.

Thanks for the update @davidchesnut !
