### ISSUE TITLE
No ID for Record button in PowerPoint

### ISSUE THREAD

**Issue by yiraeryu** [OfficeDev/office-fluent-ui-command-identifiers#12]
There are no IDs identified in the existing controls list that are specific for PowerPoint Record button on the top right. There are IDs for the Comments and Share buttons though. Can we get an updated list of controls and their IDs? 
@davidchesnut @bcoard @hugojr @microsoftopensource @msftgits

**Comment by bcoard** [comment]
Sorry for the delay here, I was confirming a few details before making changes. I should have this updated soon!
