### ISSUE TITLE
ID's for Teams outlook add-in

### ISSUE THREAD

**Issue by Thijsr1998** [OfficeDev/office-fluent-ui-command-identifiers#16]
I'm looking for the ID's of the Teams add-in buttons, specifically for the 'Meet now' option. I could not find it in the list. 

![outlook meet now](https://github.com/OfficeDev/office-fluent-ui-command-identifiers/assets/137178793/97084376-3a61-47b8-86ba-6953ff240a22)

**Comment by Rick-Kirkham** [comment]
I'm trying to find the answer internally.

**Comment by Rick-Kirkham** [comment]
Sorry it has taken so long, but I have finally been able to get information about this. The IDs of controls that are added to the ribbon as part of an add-in are not available to other add-ins. Although this button was added by Microsoft, not an external developer, it was implemented as an add-in, so it doesn't have an ID that you can use in your own add-in. 

I will close this issue now. But I will assign it to myself and I should get notification if you want to add further comments.
