### ISSUE TITLE
Word - Missing Policy ID for the Transform tab (Backstage)

### ISSUE THREAD

**Issue by mitechzone** [OfficeDev/office-fluent-ui-command-identifiers#19]
Hi @Ongion 

The latest Word list does not include an entry for the Transform tab.

![image](https://github.com/OfficeDev/office-fluent-ui-command-identifiers/assets/10508685/f466f225-0b22-4f02-af38-260d5e619683)

**Comment by Ongion** [comment]
Hey, didn't notice this until just now. I'll look into it on Monday.

**Comment by Ongion** [comment]
Hi @mitechzone!

The "Transform" tab is there, but it shows up under the Control Name "DigitalPrint", and has the Policy ID "33277".

Hope that helps!
